### ISSUE TITLE
Add Further Information in Headers

### ISSUE THREAD

**Issue by paul-ihelputech** [ben-ihelputech/policies#2]
Two headers contain incomplete or lacking documentation. These categories are the Acceptance of Terms and Conditions and the Estimate Policy. Readers may have questions or be unsure of what to expect under the aforementioned headers.

The headers in question are currently marked with the double slash operator (`//`) to make them much easier to spot.

**Comment by ben-ihelputech** [comment]
Good catch!

In the future, let's stick to markdown format. Double slashes`//`  are often used in URI's and it can be difficult to find changes this way. I suggest we stick to `*** <comment> ***` to make the effected text ***bold & italic***. Thanks.
